### ISSUE TITLE
`SocketBackoff` should allow different ports per service 

### ISSUE THREAD

**Issue by ryan-ju** [TimTosi/fishfinger#1]
I suggest changing the signature of `backoffFunc` to 
```
func(*Compose, string, string)
```
and require the user to specify services as `service:port/protocol`.

For example,
```
c.StartBackoff(backoff, "redis:9999/tcp", "mysql:8888/tcp")
```

**Comment by TimTosi** [comment]
That is a good improvement idea !

Gonna try to make it ASAP unless you want to make a PR.

**Comment by ryan-ju** [comment]
I'll make a PR

**Comment by TimTosi** [comment]
PR merged.
I also update the doc & made small change to func declaration & doc comment.
