### ISSUE TITLE
libcompose version in Godeps.json is not correct

### ISSUE THREAD

**Issue by ryan-ju** [TimTosi/fishfinger#3]
The version in Godeps.json is `01be9240473106c25ffec9658632c94000ada386`, which is incompatible:

```
type Container interface {
	ID() (string, error)
	Name() string
	Port(ctx context.Context, port string) (string, error)
	IsRunning(ctx context.Context) (bool, error)  ---> in new version, this is just bool
}
```

Should upgrade to the latest libcompose.

**Comment by TimTosi** [comment]
Thanks ! Fixing this tomorrow !

**Comment by TimTosi** [comment]
Ok, moved from Godep to new official dep tool.
Tell me if everything seems alright for you and I will close if it's good enough.
