### ISSUE TITLE
Usage issue

### ISSUE THREAD

**Issue by ghost** [TimTosi/fishfinger#4]
i am not able get the package by go get, for some systems i am able to get the package. After getting package, not able to use compose operations.
It will return the following:

# github.com/timtosi/fishfinger/vendor/github.com/docker/docker/oci
../../github.com/timtosi/fishfinger/vendor/github.com/docker/docker/oci/defaults_linux.go:19:3: unknown field 'Platform' in struct literal of type specs.Spec
../../github.com/timtosi/fishfinger/vendor/github.com/docker/docker/oci/defaults_linux.go:62:25: cannot use []string literal (type []string) as type *specs.LinuxCapabilities in assignment
../../github.com/timtosi/fishfinger/vendor/github.com/docker/docker/oci/defaults_linux.go:96:17: undefined: specs.Namespace
../../github.com/timtosi/fishfinger/vendor/github.com/docker/docker/oci/defaults_linux.go:107:14: undefined: specs.Device
../../github.com/timtosi/fishfinger/vendor/github.com/docker/docker/oci/defaults_linux.go:108:15: undefined: specs.Resources
../../github.com/timtosi/fishfinger/vendor/github.com/docker/docker/oci/devices_linux.go:15:32: undefined: specs.Device
../../github.com/timtosi/fishfinger/vendor/github.com/docker/docker/oci/devices_linux.go:27:38: undefined: specs.DeviceCgroup
../../github.com/timtosi/fishfinger/vendor/github.com/docker/docker/oci/devices_linux.go:39:85: undefined: specs.Device
../../github.com/timtosi/fishfinger/vendor/github.com/docker/docker/oci/devices_linux.go:39:116: undefined: specs.DeviceCgroup
../../github.com/timtosi/fishfinger/vendor/github.com/docker/docker/oci/namespaces.go:6:44: undefined: specs.NamespaceType
../../github.com/timtosi/fishfinger/vendor/github.com/docker/docker/oci/defaults_linux.go:108:15: too many errors
# github.com/timtosi/fishfinger/vendor/github.com/docker/libcompose/config
../../github.com/timtosi/fishfinger/vendor/github.com/docker/libcompose/config/schema_helpers.go:50:73: cannot use environmentFormatChecker literal (type environmentFormatChecker) as type gojsonschema.FormatChecker in argument to gojsonschema.FormatCheckers.Add:
	environmentFormatChecker does not implement gojsonschema.FormatChecker (wrong type for IsFormat method)
		have IsFormat(string) bool
		want IsFormat(interface {}) bool
../../github.com/timtosi/fishfinger/vendor/github.com/docker/libcompose/config/schema_helpers.go:51:61: cannot use portsFormatChecker literal (type portsFormatChecker) as type gojsonschema.FormatChecker in argument to gojsonschema.FormatCheckers.Add:
	portsFormatChecker does not implement gojsonschema.FormatChecker (wrong type for IsFormat method)
		have IsFormat(string) bool
		want IsFormat(interface {}) bool
../../github.com/timtosi/fishfinger/vendor/github.com/docker/libcompose/config/schema_helpers.go:52:62: cannot use portsFormatChecker literal (type portsFormatChecker) as type gojsonschema.FormatChecker in argument to gojsonschema.FormatCheckers.Add:
	portsFormatChecker does not implement gojsonschema.FormatChecker (wrong type for IsFormat method)
		have IsFormat(string) bool
		want IsFormat(interface {}) bool

**Comment by TimTosi** [comment]
Ah yeah, honestly, this package is sooooooo old that the glue libraries it used might probably not be up-to-date with the latest specs.

Well, from the moment this library was still helpful to know, multiple equivalent solution had been implemented in different CI tool, so I better put that repo as read only with a disclaimer, but thank you very much for having taken interest in this work. I hope you have found an adequate substitution for your issue :)
